# Zuulv3 CI setup for OpenStack.
# The build-tox-manuals-checkbuild job is defined in openstack-manuals.

- project:
    check:
      jobs:
        - build-tox-manuals-checkbuild
    gate:
      jobs:
        - build-tox-manuals-checkbuild
    promote:
      jobs:
        - promote-openstack-manuals
